name: Build and Push Kenium Music Image

on:
  schedule:
    - cron: '0 0 */14 * *'  # every 2 weeks
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this docker repo
        uses: actions/checkout@v4

      - name: Get latest commit hash from Kenium-Music
        id: get_latest
        run: |
          LATEST_COMMIT=$(git ls-remote https://github.com/ToddyTheNoobDud/Kenium-Music.git HEAD | awk '{print $1}')
          echo "Latest upstream commit: $LATEST_COMMIT"
          echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT

      - name: Check for previous commit record
        id: check_cache
        run: |
          PREV_COMMIT=$(cat .last_upstream_commit 2>/dev/null || echo "none")
          echo "Previous commit: $PREV_COMMIT"
          if [ "$PREV_COMMIT" = "${{ steps.get_latest.outputs.latest_commit }}" ]; then
            echo "🟢 No new commits in upstream repo. Skipping build."
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if no new upstream changes
        if: steps.check_cache.outputs.skip_build == 'true'
        run: exit 0

      - name: Clone upstream Kenium-Music
        run: |
          git clone https://github.com/ToddyTheNoobDud/Kenium-Music.git source
          cp -r source/* source/.* . 2>/dev/null || true
          rm -rf source
          echo "${{ steps.get_latest.outputs.latest_commit }}" > .last_upstream_commit
          echo "✅ Pulled latest Kenium-Music source"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: wishdream/kenium-music:latest

      - name: Save commit hash for next run
        run: |
          echo "Saving commit hash to cache..."
          echo "${{ steps.get_latest.outputs.latest_commit }}" > .last_upstream_commit
